// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR173Fwx9X8p6xVcn82QKILukhgvfk6mM',
    appId: '1:34526330432:web:e5ab79b5304cef8718e9a5',
    messagingSenderId: '34526330432',
    projectId: 'modern-uis',
    authDomain: 'modern-uis.firebaseapp.com',
    storageBucket: 'modern-uis.firebasestorage.app',
    measurementId: 'G-NB24YQ9MCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1TswYA9gJPzrhlusVKdiia1vFAweNe70',
    appId: '1:34526330432:android:a2c9e2cd9ff67c4e18e9a5',
    messagingSenderId: '34526330432',
    projectId: 'modern-uis',
    storageBucket: 'modern-uis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA846F_0VyfVf175lB6_JBXPGHeJzsc7L8',
    appId: '1:34526330432:ios:a45ddf08038e26eb18e9a5',
    messagingSenderId: '34526330432',
    projectId: 'modern-uis',
    storageBucket: 'modern-uis.firebasestorage.app',
    iosBundleId: 'com.example.cinexApp',
  );
}
