name: cinex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# dependencies -------------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets -------------------------
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
  
  # fonts -------------------------
  fonts:
    - family: ZalandoSansExpanded-Black
      fonts:
        - asset: assets/fonts/ZalandoSansExpanded-Black.ttf
    - family: ZalandoSansExpanded-Bold
      fonts:
        - asset: assets/fonts/ZalandoSansExpanded-Bold.ttf
    - family: ZalandoSansExpanded-Medium
      fonts:
        - asset: assets/fonts/ZalandoSansExpanded-Medium.ttf
    - family: ZalandoSansExpanded-Regular
      fonts:
        - asset: assets/fonts/ZalandoSansExpanded-Regular.ttf
    - family: ZalandoSansExpanded-SemiBold
      fonts:
        - asset: assets/fonts/ZalandoSansExpanded-SemiBold.ttf

